name: "Teste da action composite"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  job_action_test:
    name: "Job - Executando Action Composite"
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Executando Action JS"
        id: action-composite
        uses: fspelling/action-composite@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number }}
          comment: "Comentario adicionado na pipe (composite)"
      - name: "Exibindo output comentario"
        run: echo "id comentario=${{ steps.action-composite.outputs.comment-id }}"
